version: "3"
services:
  jobmanager:
        image: flink
        ports:
                - "8081:8081"
        command: jobmanager
        container_name: jobmanager
        environment:
                - |
                  FLINK_PROPERTIES=
                  jobmanager.rpc.address: jobmanager
        networks:
                - net_kafka_flink

  taskmanager:
        image: flink
        container_name: taskmanager0
        depends_on:
                - jobmanager
        command: taskmanager
        scale: 1
        environment:
                - |
                  FLINK_PROPERTIES=
                  jobmanager.rpc.address: jobmanager
                  taskmanager.numberOfTaskSlots: 2
        networks:
                - net_kafka_flink
  zookeeper:
          image: zookeeper
          hostname: zookeeper
          container_name: zookeeper
          ports:
                - '2181:2181'
          networks:
                - net_kafka_flink
  kafka0:
          image: kafka 
          ports:
                - '32000:32000'
          hostname: kafka0
          container_name: kafka0
          depends_on:
                  - zookeeper
          environment:
                - BROKER_ID=0
                - ADVERTISED_HOST=kafka0
                - ADVERTISED_PORT=32000
                - ZOOKEEPER_CONNECT=zookeeper:2181
                - LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
                - INTER_BROKER_LISTENER_NAME=INTERNAL
          networks:
                - net_kafka_flink

  kafka1:
          image: kafka
          ports:
                - '32001:32001'
          hostname: kafka1
          container_name: kafka1
          depends_on:
                - zookeeper
          environment:
                - BROKER_ID=1
                - ADVERTISED_HOST=kafka1
                - ADVERTISED_PORT=32001
                - ZOOKEEPER_CONNECT=zookeeper:2181
                - LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
                - INTER_BROKER_LISTENER_NAME=INTERNAL
          networks:
                - net_kafka_flink
networks:
        net_kafka_flink:
                driver: bridge
