# This is a basic workflow to apply AWS/Github upload
name: 'Upload Website'

# Controls when the action will run.
on:
  push:
    branches:
    - main
    - develop
    - release
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:     

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  website-ci:
    name: 'Website CI' 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Environment variables
    env:
      BUCKET_PROD: "test-frank-delete"
      BUCKET_DEV: "test-frank-delete" 
      BUCKET_QA: "test-frank-delete"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}         
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get bucket name 
        id: get-bucket-name
        run: | 
          if [[ $GITHUB_REF == "main"  ]] ; then 
            echo "bucket=${{env.BUCKET_PROD}}" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == "develop"  ]] ; then 
            echo "bucket=${{env.BUCKET_DEV}}" >> $GITHUB_OUTPUT
          else 
            echo "bucket=${{env.BUCKET_QA}}" >> $GITHUB_OUTPUT
          fi
      - name: Checkout
        uses: actions/checkout@master
      - name: Sync with S3 bucket
        uses: reggionick/s3-deploy@v3
        with:
          folder:  static  
          bucket: ${{steps.get-bucket-name.outputs.bucket}}
          bucket-region: eu-west-1



